### ISSUE TITLE
Often at startup, twitch-tui does not connect and does not throw any error

### ISSUE THREAD

**Issue by jbkkd** [Xithrius/twitch-tui#141]
**Describe the bug:**
This is a hard bug to describe as it's not persistent, and can't be accuratly reproduced.

The best I've got is that sometimes, when loading twt, it fails to connect to the chat, without throwing any error - I only see an empty list with the "Time / Username / Message content" header.

**To Reproduce:**
No good way to reproduce unfortunately.

**Screenshots:**
<img width="965" alt="image" src="https://user-images.githubusercontent.com/2523769/166961505-ec3f44b3-3898-4d99-af0c-2d2706e0005d.png">

**System:**
Mac OS 12.2.1

- Twitch-tui version:
1.6.0

- Terminal:
iTerm2 3.4.15

- Shell:
zsh

**Comment by Xithrius** [comment]
Huh, I thought I solved this problem a while back. I'll see what I can do to make the program retry the connection.

Thanks for bringing this to my attention!

**Comment by nbgibson** [comment]
Chiming in to say I've run into this before as well. Let me know if I can provide some logs or anything of that nature.

**Comment by Xithrius** [comment]
Logging hasn't been implemented in this version, I don't know how I got this far without them. They'll appear in 2.0.

I'll do my best to figure this out, although exams are occurring at this moment. Thanks in advance for your patience.

**Comment by Xithrius** [comment]
An example panic for me to stare at later:

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(Data { time_sent: "Wed May 18 20:36:24 2022", author: "System", system: true, payload: Message("Unable to connect to Twitch. Attempting to reconnect.") })', /home/xithrius/.cargo/registry/src/github.com-1ecc6299db9ec823/twitch-tui-2.0.0-alpha.3/src/twitch.rs:199:121
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Xithrius** [comment]
The https://github.com/Xithrius/twitch-tui/tree/connection-failed-fix branch has been created to fix this issue. Hopefully I'll find a solution in a decent amount of time.

**Comment by Xithrius** [comment]
The crate that I've been using has been giving me too many problems with connection issues. I've decided to rewrite the Twitch chat backend to websockets. This may take a little, but I will overall have more control over what happens.

**Comment by Xithrius** [comment]
As making an IRC message parser is going to take a while, I'm going to try to come up with a temporary solution which requires restarting the thread. Intuitively this shouldn't take too long, but with all the hardships I've encountered so far, who knows what could happen next.

**Comment by Xithrius** [comment]
This problem may have been solved in https://github.com/Xithrius/twitch-tui/releases/tag/v2.0.0-alpha.5. If you run into any problems, be sure to re-open this issue. Thanks for your patience!
