### ISSUE TITLE
Config files/directories don't get generated

### ISSUE THREAD

**Issue by AceofSpades5757** [Xithrius/twitch-tui#144]
**Describe the bug:**

In step 3, from the README, it says that the default configuration paths get generated, but that wasn't the case when running it on Windows 10. Instead, this is what I get below.

`Configuration not found. Create a config file at 'C:\Users\ME\AppData\Roaming\twt\config.toml', and see 'https://github.com/Xithrius/twitch-tui/blob/main/default-config.toml' for an example configuration.`

**To Reproduce:**

1. Install `twt` using cargo install.
2. Run `twt` in the terminal, from README step 3.
3. Go to `APPDATA` to get to configurations, given the `twt` directory.

The directory and config file(s) isn't there. I checked all the directories in my `~/AppData`, just in case and found nothing. Even checked `~/.config`, although this is a Windows machine so there shouldn't be anything there.

**Expected behavior:**

I expected a directory at `%APPDATA%\twt` (PowerShell: `$env:APPDATA\twt`).

**Screenshots:**

**System:**

- Twitch-tui version: 1.6.0

- Operating System: Windows 10 Pro - Version 10.0.19044 Build 19044

- Terminal: Windows Terminal

- Shell: PowerShell

**Additional context:**

I use the same context on Linux machines, which is why I have directories like `~/.config`.

**Comment by Xithrius** [comment]
I should be able to fix this within the hour or so. Thanks for the issue!

**Comment by Xithrius** [comment]
Sorry, took me a while to set up my VM, but I just realized the issue is to do with your version.

The main branch is the latest branch, which is currently in alpha and is unstable. `1.6.0` does not support auto-generation. The `1.6.0` README looks like [this](https://github.com/Xithrius/twitch-tui/tree/f7edafd6e999ce9b8200e906bc3790f7d2f960c2).

Sorry for the confusion. If you'd like the latest release (as of this date), you can install it through `cargo install twitch-tui --version "2.0.0-alpha.3"`

**Comment by Xithrius** [comment]
If upgrading the crate fixed the problem, please close this issue. Have a good one!

**Comment by AceofSpades5757** [comment]
I should have thought of that. I've run into this problem before. The directions from the stable version worked out just fine, thanks!

The alpha version actually has its own problem, although it _did_ create the `twt` config directory where I expected it to be. I copied the stderr below in case it'll help you later.

``` rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\ME\.cargo\registry\src\github.com-1ecc6299db9ec823\twitch-tui-2.0.0-alpha.3\src\handlers\config.rs:120:63
```

**Comment by Xithrius** [comment]
Oh dear. I'll be sure to fix that up as well.

**Comment by Xithrius** [comment]
I can see why the file wasn't copied, and not sure how I didn't catch this sooner. The binary obviously wouldn't contain the config template.

Time to modify [this line](https://github.com/Xithrius/twitch-tui/blob/c0d10b25a6a175e7e9e3f70b5313844b3290e6f7/src/handlers/config.rs#L120) to instead fetch from GitHub.
