### ISSUE TITLE
does not work when the terminal has a white background

### ISSUE THREAD

**Issue by ModProg** [Xithrius/twitch-tui#165]
![image](https://user-images.githubusercontent.com/11978847/174285319-f50a4dc0-47a5-483f-83ef-95ba9d521e88.png)

**Comment by Xithrius** [comment]
By "does not work" do you mean that it straight up doesn't function, or that you just can't see anything?

**Comment by ModProg** [comment]
I cannot see anything

**Comment by Xithrius** [comment]
Interesting issue, I'll see what I can do.

**Comment by Xithrius** [comment]
Probably going to make some theme implementation where users can create their own themes, I'll include dark/light mode generation options.

**Comment by ModProg** [comment]
You could also support a "theme" that uses the terminal colors, those should already be themed correctly.

**Comment by Xithrius** [comment]
Will start working on this now.

**Comment by yamiteru** [comment]
How's the progress on this? I use light themes everywhere and would love to use this but can't because I can't see anything.

**Comment by Xithrius** [comment]
Sorry I still somehow haven't gotten to this since I've been working on a bunch of other issues.

I am still working on this, just slowly. I'll pick up the pace now, though.

**Comment by ModProg** [comment]
looks good

**Comment by Xithrius** [comment]
Alright, I'll create the alpha soon.

**Comment by yamiteru** [comment]
I personally use Solarized Light but this is better than nothing.

**Comment by Xithrius** [comment]
I'll make it so that users are able to customize their themes, so this release would be for usability.

**Comment by shmup** [comment]
> Bottom one's username palette is `cool`.

cool

**Comment by shmup** [comment]
> I'll make it so that users are able to customize their themes, so this release would be for usability.

If you haven't seen alacritty's configuration for themes, it's a nice enough yaml configuration:

Soralized Light:
 - https://github.com/eendroroy/alacritty-theme/blob/master/themes/solarized_light.yaml


An example with even more configuration:
 - https://github.com/dracula/alacritty/blob/05faff15c0158712be87d200081633d9f4850a7d/dracula.yml

**Comment by Xithrius** [comment]
The example that I posted above was using kitty's [`Afterglow`](https://github.com/dexpota/kitty-themes/blob/master/themes/Afterglow.conf) (top) and [`Material`](https://github.com/dexpota/kitty-themes/blob/master/themes/Material.conf) (bottom), just so y'all are aware.

**Comment by Xithrius** [comment]
Dark (default) and light theme is now available through `v2.0.0-alpha.9`. More info on [this](https://github.com/Xithrius/twitch-tui/releases/tag/v2.0.0-alpha.9) release page.
