### ISSUE TITLE
No config file generated upon running twt

### ISSUE THREAD

**Issue by shmup** [Xithrius/twitch-tui#185]
Fresh install. Ran `twt` as instructed:

```
Configuration not found. Create a config file at '/home/jtm/.config/twt/config.toml', and see 'https://github.com/Xithrius/twitch-tui/blob/main/default-config.toml' for an example configuration.
```
`twitch-tui 1.6.0` compiled on `fedora` with `cargo 1.62.0`

----

By the way, incredibly cool project, v glad you were inspired to give us this. Pairs great with streamlink/mpv.

![image](https://user-images.githubusercontent.com/118710/181671899-60469301-5184-4222-9bc3-21dd386ed7cd.png)

**Comment by Xithrius** [comment]
Sorry for the confusion. The main branch README tells you that it should be generated, but the version-specific one, in your case [1.6.0](https://github.com/Xithrius/twitch-tui/tree/v1.6.0), says manual copying should be done instead.

Thanks for using this application! I also find it pairs very well with [streamlink](https://github.com/streamlink/streamlink), so I can watch streams/videos in my own media player, such as vlc.

**Comment by shmup** [comment]
Ah hah, well that settles it! Thanks for the snappy reply

**Comment by Xithrius** [comment]
No problem. Have a good one!

**Comment by shmup** [comment]
Since this is a ticket that references streamlink, I want to share a little script I made to make the whole process buttery smooth http://ix.io/45YD/sh [[raw](http://ix.io/45YD)]

**Comment by Xithrius** [comment]
Could you paste that script here in a code block instead? Thanks!

**Comment by shmup** [comment]
Edited and updated!

**Comment by Xithrius** [comment]
Very cool. I'll see if it's possible at all to implement streamlink with this in a future update, as pyo3 doesn't support 3rd party packages.

**Comment by shmup** [comment]
That is an _excellent_ idea. Also, I started a discussion with this script!

I've updated it to start `mpv` in the background and just go ahead and run `twt` right then and there!

https://github.com/Xithrius/twitch-tui/discussions/186
