### ISSUE TITLE
Doesn't show messages if channel name has uppercase characters

### ISSUE THREAD

**Issue by Rik034** [Xithrius/twitch-tui#223]
**Describe the bug:**
If the channel name has uppercase letters in it, no messages are loaded.

**To Reproduce:**
1. Either provide a channel with uppercase letters in it in the config or with -c
2. Run twt
3. See bug

**Screenshots:**
![test](https://user-images.githubusercontent.com/60218806/192694723-ff87a7d8-ab04-4da5-b643-4ddee30259b8.gif)
Left side is twt -c xqc, right side is twt -c xQc

**System:**
- Twitch-tui version: tested on 1.6.0, 2.0.0-alpha.11

- Operating System: Arch Linux w/ kernel 5.19.11-xanmod1-1-x64v2

- Terminal: alacritty 0.10.1

- Shell: zsh 5.9

**Additional context:**
I pipe [this script](https://github.com/nbgibson/streamers) to see which channels that I follow are online into dmenu to open twt and streamlink. The channel name given by that script is the name that shows up on twitch, so it might have uppercase letters. It's not a big deal, I just convert the uppercase letters to lowercase in my dmenu script, but I was wondering what causes this issue, because in the logs it says that it connected to the irc channel and it even shows the info (like follower mode, slow mode etc.)

**Comment by Xithrius** [comment]
Very interesting, I'll see what's causing this problem.

**Comment by Xithrius** [comment]
According to [this Twitch developers forum post](https://discuss.dev.twitch.tv/t/are-twitch-names-case-sensitive/20398/2), when joining an IRC channel, the characters have to be lowercase. 

I'll make a hotfix, and it'll be put out in the next release (very soon).

**Comment by Rik034** [comment]
> According to [this Twitch developers post](https://discuss.dev.twitch.tv/t/are-twitch-names-case-sensitive/20398/2), when joining an IRC channel, the characters in a channel name have to be lowercase.

I thought it might be something along those lines.
Thanks for the quick reply!

**Comment by Xithrius** [comment]
No problem.

In terms of frontend, do you think that the `channel` title at the top of the window should reflect Twitch's IRC channel rule, or should it reflect what the user inputs?

**Comment by Xithrius** [comment]
I've gone with the option of lowercase channels in the title. This was implemented in ab6f2af0c78def0b7c95f450325f5dd118020f24.

This hotfix is included with the state tabs feature in release [`v2.0.0-alpha.12`](https://github.com/Xithrius/twitch-tui/releases/tag/v2.0.0-alpha.12).

Thank you for catching this issue, have a good one!
