### ISSUE TITLE
Start the app in insert mode

### ISSUE THREAD

**Issue by lukepighetti** [Xithrius/twitch-tui#238]
<img width="720" alt="Screen Shot 2022-10-17 at 12 43 42 PM" src="https://user-images.githubusercontent.com/666539/196235379-a43a4415-4bbe-4dd3-8977-11f8cbffef1d.png">

As a new user I thought the app was broken because I didn't see any way to send a message, no logs, and no errors

**Comment by Xithrius** [comment]
Thank you for creating the issue. I will make the documentation more intuitive, and I'll also see what I can do about the UI.

I'll probably make a config/CLI option so you're able to start in the mode of your choice, but I think the default startup mode should still remain.

**Comment by Xithrius** [comment]
Solved in 2a9e793735c7304a7acb0372539798fd7dcd8368
