### ISSUE TITLE
Remove token from config file

### ISSUE THREAD

**Issue by lukepighetti** [Xithrius/twitch-tui#239]
I keep all my secrets outside of ~/.config and rely on environment variables. Would be nice to be able to provide an environment variable `TWT_TOKEN` instead of having to put it in `~/.config/twt/config.toml` `twitch.token`

**Comment by Xithrius** [comment]
Good idea. I'll probably make it so that the application will search for an environment variable first, before attempting to fetch from the config file.

**Comment by Xithrius** [comment]
Sorry for the delay, university exists. This feature is being implemented and will be released in the next alpha.
