### ISSUE TITLE
Change input cursor from box to line

### ISSUE THREAD

**Issue by ModProg** [Xithrius/twitch-tui#263]
**Describe the solution you'd like**
When in "insert" mode make the cursor a vertical line. (like `guicursor` in neovim)

**Additional context**
Escape sequences documented here: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-Ps-SP-q.1D81

**Comment by Xithrius** [comment]
I've looked into this, and I'm just not sure how to do it properly. `tui-rs` doesn't seem to control the cursor format, and `rustyline` just controls input.
