### ISSUE TITLE
Add features list to the readme

### ISSUE THREAD

**Issue by its-justus** [Xithrius/twitch-tui#267]
**Is your feature request related to a problem? Please describe.**
Coming to the repo for the first time there is very little indication of what features twitch-tui currently offers or will offer in the future. As it is the readme just shows that you can get twitch chat in a terminal.

**Describe the solution you'd like**
The addition of a succinct list of major features to the readme. This would include things like "Twitch OAuth login, connecting to multiple channels, emoji support (future), ..." This lets users and contributors know what features are available and planned at a glance.

**Describe alternatives you've considered**
The same but located in documentation instead. If the feature list gets too long, then perhaps major features could be listed in the readme with a link to a full feature list in documentation.

**Comment by Xithrius** [comment]
Thanks for the issue!

Good idea, I shall do this.

For the future, the preview image in the README will become a view.

Thanks again!

**Comment by Xithrius** [comment]
Done in 82de6663b473e982baa0270e69b51aea6ebe5c29. Can be seen [here](https://github.com/Xithrius/twitch-tui#feature-list).
