### ISSUE TITLE
Make timestamp column smaller or toggleable

### ISSUE THREAD

**Issue by its-justus** [Xithrius/twitch-tui#268]
**Is your feature request related to a problem? Please describe.**
The timestamp column takes up a large chunk of UI real estate while not offering much value. 

**Describe the solution you'd like**
Render the timestamp in a more concise format (eg. HH:MM:SS AM) to limit the column size.

**Describe alternatives you've considered**
Another option would be to make the timestamp toggleable since they are more of a nice to have than a must have. Both features would be nice!

**Comment by Xithrius** [comment]
You can turn off the date column within the config using the [`date_shown`](https://github.com/Xithrius/twitch-tui/blob/main/default-config.toml#L35) boolean value, and you can have a specific format using the [`date_format`](https://github.com/Xithrius/twitch-tui/blob/main/default-config.toml#L37) value.

**Comment by Xithrius** [comment]
The OS-specific config file path can be seen [here](https://xithrius.github.io/twitch-tui/guide/configuration.html#config-file)

**Comment by Xithrius** [comment]
Given that this issue is already implemented, I shall close this issue. Feel free to continue discussion if you have any more questions.
