### ISSUE TITLE
Audit Keybinds Documentation With Source Code

### ISSUE THREAD

**Issue by blakexcosta** [Xithrius/twitch-tui#275]
**Describe the solution you'd like**
Make sure that the keybinds guide rendered at (1.0) and done in markdown at (1.1) line up with the actual keybinds in rust done at (1.2).

**Describe alternatives you've considered**
N/A, at request of @Xithrius 

**Additional context**
Links are as follows:
1.0: https://xithrius.github.io/twitch-tui/keybinds/index.html
1.1: https://github.com/Xithrius/twitch-tui/tree/main/book/src/keybinds
1.2: https://github.com/Xithrius/twitch-tui/blob/main/src/handlers/user_input/input.rs

**Comment by blakexcosta** [comment]
Issue 1 Documentation:


I went through and looked at your source code, and made notes of the following functionality with each mode.  I will update as i keep going through each. @Xithrius is this the best place to put this or would you prefer if I put as an issue on the github?


Normal Mode Audit:
c = goes to chat window
s = channel switch dialogue pops up
ctrl + f = searches messages
ctrl + t = toggles filter on and off.
ctrl + r = reverse filter toggle
i = opens up message input prompt
@ = opens up message input prompt with @ symbol ready
/ = opens up message input prompt with / symbol ready
ctrl + p = triggers panic and exits program
? = opens up Help option and lists all commands
q = quits program
Esc = exits any layers/ prompts and goes back to the base/normal view.


Insert Mode Audit:
ctrl + f = moves cursor one space to the right
ctrl + b = moves cursor one space to the left 
ctrl + a = moves cursor to the beginning of the messge
ctrl + e = moves cursor to the end of the message

Note: I am running a Mac, alt keywords do not perform as intended, notes as to functionality are listed below:
alt + f = appends f to where the cursor is. documented functionality not performed.
alt + b = does nothing. documented functionality not performed.

**Comment by Xithrius** [comment]
> `alt` keybinds do not work as intended on mac due to lack of Alt keyword. Suggestion: Add Option/Mac support for Alt keywords? Curious on feedback on this.

Interesting. I will find a solution to this, although so far I don't see an `option` keycode, at first glance. Gonna dig deeper.

**Comment by Xithrius** [comment]
What terminal are you using?

**Comment by blakexcosta** [comment]
I'm using zsh for my terminal. I've tested in a vscode terminal instance as well (which I believe is also running zsh).

For reference, my Mac (at least the one I'm currently using) does not have an `alt` key but does contain `fn` `control` `option` and `command` keys.

Macs are cool, but weird.

**Comment by Xithrius** [comment]
I also have a mac machine, so I'll test this application with the option key in the near future. By terminal I mean the emulator, and not the shell.

Shells examples are bash, zsh, fish, which terminal emulator examples are iterm 2, kitty, alacritty.

**Comment by blakexcosta** [comment]
Just the default Terminal (i.e. 'Terminal') application that comes pre-installed, nothing special like iTerm or iTerm2 etc.

**Comment by Xithrius** [comment]
I believe that iterm2 is much better than the regular terminal application, due to the customization and overall amount of features it contains. I would recommend it very much.

**Comment by blakexcosta** [comment]
Sounds good, I appreciate the suggestion and I will implement that into my workflow

**Comment by Xithrius** [comment]
Alright, after testing on my mac I can see the pretty bad input problem. Instead of going to the end of the next word with `option + w`, the summation symbol is inputted.

I'll probably make a configuration option to route `option` to something else on macos.

**Comment by Xithrius** [comment]
Do you have a suggestion to what `option` should be rebound to? Doesn't look like it can be used as a leader key.

**Comment by Xithrius** [comment]
I believe the keyboard guide is fine at this time.
