### ISSUE TITLE
Consolidate msg_cells  Declaration

### ISSUE THREAD

**Issue by blakexcosta** [Xithrius/twitch-tui#276]
**Is your feature request related to a problem? Please describe.**
The msg_cells variable at (4.0) has an almost 50 line declaration, split it up and/or document to make it more intuitive.

**Describe the solution you'd like**
Consolidate to be shorter and/or follow up with more fleshed out documentation

**Describe alternatives you've considered**
N/A - Request from @Xithrius 

**Additional context**
Provided via message from discord [link](https://discord.com/channels/273534239310479360/1051823062133243935/1054577629619032074)

**Comment by Xithrius** [comment]
Nevermind, this isn't needed. I've documented it so it's easier on my mind and others in the future.
