### ISSUE TITLE
Duplicates all keys because key-down and key-up both trigger input

### ISSUE THREAD

**Issue by gavinbeatty** [Xithrius/twitch-tui#333]
**Describe the bug:**
All key-down AND key-up events trigger input, leading to duplicates.

**To Reproduce:**
Press i go to into text insert mode, and another "i" will appear immediately in the input text box. Press any other key, and the key will appear on key-down AND on key-up, meaning it appears twice. This includes Backspace, so it is impossible to enter a single character, even by correcting one character at a time.

**Expected behavior:**
Input only detected on key-down or repeats on longpress key-down.

**Screenshots:**
None.

**System:**
- Twitch-tui version: 2.1.0

- Operating System: Microsoft Windows 10 Pro
- Version: 10.0.19045 Build 19045

- Terminal: wezterm 20230408-112425-69ae8472 (installed via scoop)
- Terminal: windows-terminal 1.16.10261.0 (installed via scoop)

- Shell: PowerShell 7.3.3

**Additional context:**
None.

**Comment by gavinbeatty** [comment]
- twitch-tui installed via `cargo install twitch-tui --version "2.1.0"`.
- cargo installed via `rustup toolchain install stable-x86_64-pc-windows-msvc --profile minimal`
- rustup 1.25.2 (installed via scoop)

**Comment by Xithrius** [comment]
Alright. Gonna go test on my windows install to see if this is reproducible.

**Comment by gavinbeatty** [comment]
Cool. Just tested that this happens with cmd.exe as well, so no need to install any terminals or shells.

**Comment by Xithrius** [comment]
If I was to make a branch with the fix, would you be willing to checkout said branch to see if it works properly?

**Comment by gavinbeatty** [comment]
Sure, no problem, no rush.

**Comment by Xithrius** [comment]
Alright. The fix will be done.

**Comment by Xithrius** [comment]
Just to make sure, state switching with `i`, `?`, `s`, etc works but user text input does not?

**Comment by Xithrius** [comment]
A patch has been pushed to https://github.com/Xithrius/twitch-tui/tree/fix-duplicate-keys.

**Comment by gavinbeatty** [comment]
Tested and it fixes this bug. Thanks!

**Comment by Xithrius** [comment]
Very well. I'll merge this into main and make a quick release for it.

**Comment by Xithrius** [comment]
74d4240011e65feb9f09811b7570876507368cd7

**Comment by Xithrius** [comment]
Now available in https://github.com/Xithrius/twitch-tui/releases/tag/v2.2.0
