### ISSUE TITLE
Not working on Amazon Linux 2

### ISSUE THREAD

**Issue by MotaOcimar** [Xithrius/twitch-tui#336]
**Describe the bug:**

I'm using an AWS EC2 instance. The program has been successfully installed.
But when I run `twt`, the screen doesn't refresh with the chat messages.
If I try to send a message it only shows my message, but I believe it is not published in the chat for real

![image](https://user-images.githubusercontent.com/29007115/231784177-5832aa76-0090-44b6-91a7-9d2e2d2869bc.png)

**To Reproduce:**

1. Create an EC2 AWS instance
2. Install twitch-tui
3. Do the initial setup
4. Join the chat with `twt` or `twt -c <channel>`

**Expected behavior:**

I expected to see other users' messages, as well as being able to interact by sending my own messages.

**System:**

- Twitch-tui version: 2.1.0

- Operating System: Amazon Linux release 2 (Karoo)

- Terminal: Windows Terminal; Termux

- Shell: fish 3.6.1; bash 4.2.46
Both through ssh

**Additional context:**
Everything works fine if I install it on my local machine (Windows with Subsystem for linux running fish or bash, also in Windows terminal)

**Comment by Xithrius** [comment]
Have you tried restarting the twt instance? There's been problems with connecting to Twitch's IRC, I'm still figuring them out to this day.

**Comment by MotaOcimar** [comment]
I've tried closing twt and starting it again (if that's what you mean by restarting the twt instance). I also tried several times to uninstall and install it again.

About Twitch IRC, how do I know if there was a problem connecting?

**Comment by Xithrius** [comment]
Could you run `twt -l log.log --verbose` and paste the output here in a code block?

**Comment by Xithrius** [comment]
Actually, I seem to have found a solution to the connection issue. I'll push out a patch.

**Comment by Xithrius** [comment]
Release https://github.com/Xithrius/twitch-tui/releases/tag/v2.2.1 should fix your issue. Just in case it doesn't, I'll be keeping this issue open.

**Comment by MotaOcimar** [comment]
It still not working :(

I installed the patch release, but the problem remains.

Running with `twt -l log.log --verbose` I got the following log:

```
[2023-04-15][07:07:37][twt][INFO] Logging system initialised
[2023-04-15][07:07:37][twt][INFO] Started tokio communication channels.
[2023-04-15][07:07:37][twt::terminal][INFO] Started UI driver.
[2023-04-15][07:07:37][twt::twitch][INFO] Spawned Twitch IRC thread.
[2023-04-15][07:07:37][irc::client::conn][INFO] Connecting to irc.chat.twitch.tv.
[2023-04-15][11:09:24][twt][INFO] Logging system initialised
[2023-04-15][11:09:24][twt][INFO] Started tokio communication channels.
[2023-04-15][11:09:24][twt::terminal][INFO] Started UI driver.
[2023-04-15][11:09:24][twt::twitch][INFO] Spawned Twitch IRC thread.
[2023-04-15][11:09:24][irc::client::conn][INFO] Connecting to irc.chat.twitch.tv.
```

Unfortunately it doesn't seem useful to me.

**Comment by Xithrius** [comment]
Can you post your config file contents? (Excluding the token, of course)

**Comment by MotaOcimar** [comment]
Of course

```
[twitch]
username = "oshimaru23"
channel = "zakl1k"
server = "irc.chat.twitch.tv"
token = "<token>"

[terminal]
tick_delay = 30
maximum_messages = 150
verbose = false
start_state = "Normal"

[storage]
channels = false
mentions = false

[filters]
enabled = false
reversed = false

[frontend]
date_shown = true
date_format = "%a %b %e %T %Y"
username_shown = true
palette = "pastel"
title_shown = true
margin = 0
badges = false
theme = "dark"
username_highlight = true
state_tabs = false
cursor_shape = "user"
blinking_cursor = false
inverted_scrolling = false
twitch_emotes = false
betterttv_emotes = false
seventv_emotes = false
```

**Comment by Xithrius** [comment]
I don't see any problems with your config. Time for me to pop open a VM and see if I can reproduce.

**Comment by MotaOcimar** [comment]
With the AWS free tier you can get a EC2 instance. Maybe it can help

**Comment by Xithrius** [comment]
Sorry that I haven't gotten around to this, I was focusing on a major rewrite for the backend.

I will try to reproduce this issue within the next week.

**Comment by Xithrius** [comment]
I've been busy with university, haven't been able to get around to this. Gonna try to reproduce today.

**Comment by Xithrius** [comment]
Alright, here are the steps that I've taken to reproduce from a clean EC2 instance, matching the specs that you've given.

1. Install Rust through `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
2. Got build dependencies for the `cc` linker and `openssl` through `sudo yum groupinstall "Development Tools"` and `sudo yum -y install openssl openssl-devel`
3. Create a `$HOME/tmp` directory due to `/tmp` only having 400mb, therefore not being able to act like a cache for 300 compiled crates.
4. Installed `twitch-tui`'s latest version through `TMPDIR=$HOME/tmp cargo install twitch-tui`
5. Copied your config (for my own sanity) with my token to `~/.config/twt/config.toml`
6. Run `twt`
7. Unable to get messages, send messages.
