### ISSUE TITLE
Listing users.

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/twitch-tui#35]
Seeing who's in chat within a different window, either to a side of the main chat window, or layered.

**Comment by Xithrius** [comment]
Closing for now due to Twitch not directly supporting user lists.

**Comment by LordMZTE** [comment]
As a workaround (though this only works for small channels, the server won't send anything above 50 viewers or so), we could send the IRC server a `CAP REQ twitch.tv/membership`, which will make it send `JOIN`/`PART` notifications which we could keep track of to build a user list. The documentation for this seems to no longer exist on Twitch's website, but I found a capture here: https://web.archive.org/web/20240301131750/https://dev.twitch.tv/docs/irc/membership/

Despite no longer being documented, this does work at the time of writing (tested with the tiny IRC client).

**Comment by Xithrius** [comment]
Not a bad idea, however since I've started looking into how I can rewrite this application to websockets (IRC is no longer recommended by twitch), I've come across this API that can be called:

https://dev.twitch.tv/docs/chat/irc-migration/#irc-commands-with-limited-or-no-equivalent

It does require that you're either a moderator/VIP, and as of #671 the solution is most likely going to be building a list of users off of who's used the chat. Maybe that IRC response can be used for now, but it'll have to be dropped when websockets is implemented.
