### ISSUE TITLE
Support multiline messages

### ISSUE THREAD

**Issue by KittyBorgX** [Xithrius/twitch-tui#352]
Twitch UI chat supports multiline messages with `SHIFT-enter` so it'd be good to have that. I do not think IRC escapes characters by default so it'd be worthwile to check for any alternatives.

**Comment by Xithrius** [comment]
Development started in https://github.com/Xithrius/twitch-tui/tree/shift-enter

**Comment by Xithrius** [comment]
For some reason I can't get `Shift + Enter` exist at all. `Enter` with any modifier seems to not register in crossterm correctly. I believe I saw an upstream issue for it at some point.

**Comment by Xithrius** [comment]
Tracking issue is now at #487
