### ISSUE TITLE
IRC Client panic on unstable connection

### ISSUE THREAD

**Issue by Nogesma** [Xithrius/twitch-tui#373]
**Describe the bug:**
When using an unstable connection, a panic can occur in twitch/connection.rs:28. In my case it was a DNS lookup failure.
It would be best to not unwrap and retry the create_client_stream with a growing timeout.  

**To Reproduce:**
- Launch twitch tui. 
- Disconnect from network. 

**Expected behavior:**
Don't panic!

**System:**
- Twitch-tui version: main#f32b22
- Operating System: Arch Linux - Linux 6.3.1

I can make a PR if needed.

**Comment by Xithrius** [comment]
Hello! Hope you've been well, and thanks for reporting this issue. You can go ahead with a PR if you'd like.
