### ISSUE TITLE
error while loading shared libraries libssl.so.1.1

### ISSUE THREAD

**Issue by rothgar** [Xithrius/twitch-tui#393]
**Describe the bug:**

Running `twt` gives the following error on Ubuntu 22.04

```
twt: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
**To Reproduce:**

I'm running on Ubuntu 22.04 and installed `twt` via cargo.

I installed the libssl1.0.0 package but still receive the error.
I tried installing libssl1.0-dev but received the error (not sure if this package is required)

```
The following packages have unmet dependencies:
 libssl1.0-dev : Depends: libssl1.0.0 (= 1.0.2n-1ubuntu5.3) but 1.0.2n-1ubuntu5.9 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Expected behavior:**

**Screenshots:**

**System:**

- Twitch-tui version:
Cannot run

- Operating System: Ubuntu 22.04.2 LTS w/ kernel 5.19.0-43-generic

- Terminal: Black box and gnome terminal

- Shell: zsh 5.8.1

**Additional context:**

**Comment by Xithrius** [comment]
This isn't a problem with `twitch-tui`, but instead with your system. I am unable to reproduce within a Ubuntu 22.04 docker container after the following steps:

1. Installing rust through `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
2. Essential packages with `sudo apt install build-essential pkg-config libssl-dev`
3. Install the `twt` executable through `cargo install twitch-tui`
4. Running `twt` runs without error.

**Comment by rothgar** [comment]
Thanks, I assumed it was a problem with my system but wasn't sure if others had problems on 22.04. I'll check why it's requiring libssl 1
