### ISSUE TITLE
Give channel switcher a result window

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/twitch-tui#425]
The follower widget looks like this, probably a good idea for the channel switcher to have the same look.

![image](https://github.com/Xithrius/twitch-tui/assets/15021300/41e2dd18-7a70-49ab-a43b-e155236ba772)

**Comment by Dark-Sol** [comment]
That has a really nice clean look to it!

**Comment by Xithrius** [comment]
79e570d0fff9d30cdc5d21e013b08adaef99f5a6
