### ISSUE TITLE
Remove messages from chat which was deleted

### ISSUE THREAD

**Issue by Doodidan** [Xithrius/twitch-tui#437]
**Is your feature request related to a problem? Please describe.**
If streamer or their moders delete a message this message will be displayed anyway. 

**Describe the solution you'd like**
The message should be removed from chat when it was deleted on twitch.

**Describe alternatives you've considered**
Now the only way I fount out is to spam chat to hide the message by chat height.

**Comment by Xithrius** [comment]
Thanks for the issue. I'll see what I can do.

**Comment by Xithrius** [comment]
Will be drafting a release in the near future
