### ISSUE TITLE
CLEARCHAT IRC Tag should only fully clear the chat if the target-user-id is not specified

### ISSUE THREAD

**Issue by Nogesma** [Xithrius/twitch-tui#441]
**Describe the bug:**
When receiving the clearchat command from twitch, if the `target-user-id` tag is specified, it should only clear the messages from the specified user, not the whole chat.

**To Reproduce:**
Timeout or ban someone from a chat, the chat will be fully cleared, instead of just deleting the user's messages. This happens a lot on large twitch streams, it shouldn't be too hard to find. 

**System:**
- Twitch-tui version: main (30f4fe45be64c7c81dc276e37c67b1fcf24f394c)

**Comment by Xithrius** [comment]
Thanks. I'll implement this.
