### ISSUE TITLE
Configurator does not save input

### ISSUE THREAD

**Issue by Dark-Sol** [Xithrius/twitch-tui#447]
**Describe the bug:**
Configurator does not save a user's input into `config.toml` if `config.toml` does not already exist.

**To Reproduce:**

1. Install a clean instance of Twitch-tui.
2. Run `twt` at the command prompt.
3. Enter all the data at the prompts given by the configurator.
4. Twitch-tui should open and be usable due to the user entering their OAuth token.
5. Close Twitch-tui.
6. Rerun `twt`.
7. The configurator reruns due to `config.toml` not retaining the data previously entered.

**System:**

- Twitch-tui version: 2.5.1

- Operating System: Windows 10

- Terminal: Terminal Preview

**Comment by Xithrius** [comment]
Thanks for the issue. I'll get a fix going.

**Comment by Xithrius** [comment]
Fixed in 142a0c2a8045fd75e3022d171fe7ce7fd508e00d
