### ISSUE TITLE
Passing a channel's name as an argument for overriding channel in config.toml

### ISSUE THREAD

**Issue by lgcavalheiro** [Xithrius/twitch-tui#46]
Hi! I've been using twt for a bit now and i felt the need to be able to override the channel property inside config.toml, since having to alter the file every time i wanted to switch channels was getting a bit cumbersome. So i hacked something real quick on my machine to achieve that: 

``` rust
let mut cloned_config; 
let ui_config;

if env::args().len() > 1 {
    let args: Vec<String> = env::args().collect();
    let channel: String = args[1].clone();
    cloned_config = config.clone();
    cloned_config.twitch.channel = channel;
    ui_config = cloned_config.clone();
} else {
    cloned_config = config.clone();
    ui_config = cloned_config.clone();
}
```
So, i was wandering... would having this as an offical feature for twt be of interest? If so, i think i could contribute with that. Not with the code above of course, i hacked that real quick and prior to that i had no experience with Rust, i'd have to take some time to study and then contribute.  Many thanks for the software! :)

**Comment by Xithrius** [comment]
Thanks for the issue! Yes, this will be a feature in the near future, I'm in the process of making upgrades for this application so programming new parts isn't as painful. 

AKA This TUI isn't nearly modular enough, but once that happens lots of progress will be made, including this.

**Comment by lgcavalheiro** [comment]
Ok! So, i'll just wait for the changes then. Thanks for the quick reply!

**Comment by Xithrius** [comment]
@lgcavalheiro Sorry for the wait, finally making some progress on this feature, shall be rolling out a release in a reasonable amount of time.
