### ISSUE TITLE
Allow using smaller than supported terminals

### ISSUE THREAD

**Issue by ModProg** [Xithrius/twitch-tui#460]
I like to have a very slim chat window, for that I would like to skip the check for supported screen size.

Maybe we could have a `--unsupported-screen-size` flag or something like that in case you want to avoid accidentally running into glitches due to small terminal sizes.

**Comment by Xithrius** [comment]
Hello. Sounds pretty reasonable to me. I'll see what I can do.

**Comment by Xithrius** [comment]
Added in 61e060d9a15b64a865441ce6e3ca8a30a399564d. Will be available in the next release.

**Comment by tgharib** [comment]
This feature appears to work if I manually pass in the `-u` flga but setting the config option `show_unsupported_screen_size` to `true` or `false` seems to have no effect. I tested on v2.6.0.

**Comment by Xithrius** [comment]
I'll take a look into this

**Comment by Xithrius** [comment]
Fixed in 5fc4399c6be46dc2d6c8f48920cac73d8836617c

**Comment by Xithrius** [comment]
Available in https://github.com/Xithrius/twitch-tui/releases/tag/v2.6.1
