### ISSUE TITLE
Add listing of available emotes to use in a channel alongside their text equivalent

### ISSUE THREAD

**Issue by lgcavalheiro** [Xithrius/twitch-tui#506]
**Is your feature request related to a problem? Please describe.**
At the moment, i have to memorize the emotes i want to use in a given chat room in order to use them, since i can't copy or get the text equivalent from someone else in chat, what ends up happening is that i have to open my browser or pull out my phone just to check the text equivalent of an emote in order to use it inside twt.

**Describe the solution you'd like**
A screen that i can open with a shortcut, said screen would then list all emotes available to use in the chat room i'm currently in, with maybe their text equivalent adjacent to them or a way for me to click/select them to use in chat.

**Describe alternatives you've considered**
Or at least a way to copy an emote used in chat by someone else already, so i can use it myself.

**Additional context**
I don't have much of a relevant experience with Rust so i don't really know how viable this is, just throwing the idea out there.

**Comment by Xithrius** [comment]
Thank you for the suggestion! I'm all for it. @Nogesma, do you want to take a shot at this? If not, I will.

**Comment by Nogesma** [comment]
Yes I can look to implement this. I also was thinking of maybe displaying the emote name on hover, but I'm not sure if it would be possible. I'll look into it.

**Comment by Xithrius** [comment]
Hello @Nogesma did you take a poke at this? I was thinking of making an attempt, unless you already have, or are still  planning to. Thanks!

**Comment by Nogesma** [comment]
Hey, sorry for not updating you on this, I have it working but it still needs a few finishing touches, I made a draft PR at #524.

**Comment by Xithrius** [comment]
Very cool. Thank you!

**Comment by Xithrius** [comment]
Available in https://github.com/Xithrius/twitch-tui/releases/tag/v2.6.4. Can be activated through `Alt + e` when the chat input box is open.

**Comment by mtane0412** [comment]
How can I use emote picker on MacOS kitty?
I tried Option + e and nothing happens.

**Comment by Xithrius** [comment]
Hmm you should be able to, I'll take a look into this. Please in the meantime create a separate issue.
