### ISSUE TITLE
[Bug] Emotes not scrolling propperly on kitty

### ISSUE THREAD

**Issue by lgcavalheiro** [Xithrius/twitch-tui#530]
**Describe the bug:**
Overtime (specially on high traffic chats) some emotes will stop scrolling and impair visualization of chat messages on kitty (haven't tested on other terminals with graphics protocol support). Resizing the terminal temporarily solves the issue, but it will occur again overtime (the higher the traffic, the faster it occurs it seems). I don't know if this is a twt specific issue or something exclusive to how my system is setup, but i decided to at least inform you of this.

Edit: I noticed that my twt is out of date, so i updated it and am testing this again, if the issue still persists i'll post below.

**To Reproduce:**
Connect to a high traffic chat and wait a bit

**Expected behavior:**
Emotes should be scrolling normally 

**Screenshots:**
[issue.webm](https://github.com/Xithrius/twitch-tui/assets/10094385/0cd85097-7df5-4c2a-9fba-abb5b06d7ac6)

**System:**

- Twitch-tui version: twitch-tui 2.6.1

- Operating System: Linux 5.15.146-1-MANJARO x86_64 GNU/Linux
- Window manager: dwm-6.3

- Terminal: kitty 0.31.0

- Shell: Bash 5.2.21(1)-release

**Additional context:**

**Comment by Xithrius** [comment]
Thank you for the issue! I'll see if I can reproduce on my system as well.

**Comment by Nogesma** [comment]
This should be fixed in 2.6.2 as I switched to using unicode placeholders for displaying emotes.
There was probably some edge case where the function clearing the emotes was not called when some messages went out of screen.
It should not be a X11/Wayland related issue.

**Comment by Xithrius** [comment]
If 2.6.2 did not in fact fix the problem, please reopen this issue.

Thanks!
