### ISSUE TITLE
Emotes not working with WezTerm under Windows 11

### ISSUE THREAD

**Issue by FlamingPhoenix40** [Xithrius/twitch-tui#538]
**Describe the bug:**
Found your program, wanted to try it out on my main Windows 11 installation. Followed instructions to install, installed WezTerm because I wanted to try it out with the emote support turned on. With default settings, program works fine. However, as soon as I turn emote support on in the config file, I get the error message: 
"This terminal does not support the graphics protocol.
Use a terminal such as kitty or WezTerm, or disable emotes."

even though I'm calling the program from WezTerm. 

**To Reproduce:**
1. Install twt from Rust Cargo.
2. Install WezTerm from official Windows Binary
3. Walk through initial setup provided when running twt for first time
4. edit config.toml to enable emote support
5. start twt from WezTerm
6. twt doesn't start but gives error message about unsupported terminal

**Expected behavior:**
twt starts with emote support enabled

**Screenshots:**

![image](https://github.com/Xithrius/twitch-tui/assets/144808356/61672373-9d28-46a3-8e5f-e71984028ace)
![image](https://github.com/Xithrius/twitch-tui/assets/144808356/f0bf6fca-a3b0-4fa7-bce6-9a7bcd653cf2)

**System:**

- Twitch-tui version: 2.6.3

- Operating System: Windows 11 23H2

- Terminal: WezTerm 20240203-110809-5046fc22

- Shell: tried both default cmd.exe in WezTerm as well as bash 5.2.15(1)-release

**Additional context:**
Could be that I'm very much missing something while setting everything up here, but as far as I can tell from the official documentation from twt, I should have done everything right.

**Comment by Xithrius** [comment]
Hello! Thank you for the issue. I believe you're doing everything right, by what you've said.

I'll try to reproduce and fix the issue, since I think I've found what's causing it.

**Comment by Nogesma** [comment]
I think it's my bad for not updating the message, I dropped Wezterm support when I introduced unicode placeholders, as Wezterm does not support it yet.
I think twt version 2.6.1 is the last one which doesn't use unicode placeholders, so it should work with wezterm, although I don't have windows so I cannot test it on there.

**Comment by Xithrius** [comment]
Ah, I see. I thought the solution was that this and operator was supposed to be an and. Tested it, broke many things.

**Comment by Nogesma** [comment]
Well, terminal emulators that do not support graphics protocol should ignore the graphics protocol query in theory, but some do not, and some terminals do not even respond to the send device attribute query `csi!("c")`, which would result in an infinite loop. 
That's why I added the env check, as kitty will always respond to those queries correctly.

If it is needed I can look into adding back the code to display emotes without unicode placeholders behind a feature flag, but the code is a lot more complicated than when using unicode placeholders. There is also a few bugs in there like #530.

**Comment by mspi21** [comment]
Hi, I just wanted to report having a similar problem with Kitty on Ubuntu Linux 23.10, the unicode boxes show up in place of emotes, but no images. `icat`ing the emotes saved in `.cache/twt/` works fine.

Versions:
twitch-tui 2.6.4
kitty 0.26.5
GNOME 45.2

Not sure what else could be relevant, feel free to ask me for additional info.

**Comment by Xithrius** [comment]
This sounds like a different problem to the current one. Could you open up a new issue? Thanks!

**Comment by AnonymouX47** [comment]
Even if Wezterm did support Unicode placeholders, there's no point trying it on Windows anyways.

See https://github.com/wez/wezterm/issues/1673.

**Comment by Xithrius** [comment]
I'll mark this as closed for now. [Error message](https://github.com/Xithrius/twitch-tui/blob/main/src/handlers/config.rs#L520) has been updated to reflect what twt currently supports.
