### ISSUE TITLE
Twitch /me command is not handled correctly

### ISSUE THREAD

**Issue by Nogesma** [Xithrius/twitch-tui#539]
When a user sends a message like `/me foo`, twitch will send the IRC CTCP command `ACTION foo`, which is not handled by the irc crate. It will pass this command as a PRIVMSG, which looks like this: `\u{1}ACTION foo\u{1}` .

The first issue is that the `\u{1}` are not escaped, so we encounter the same alignment issue as with the `\u{e0000}` character.
The second one is that the message is supposed to be colored with the color of the username of the user that sent the message, with the ACTION part removed from the message.

I can implement a fix for this. I only have one question.

As I don't think the username color that is displayed by twt is the one from twitch, would you prefer to have the message displayed with the color of the username that is used by twt or the one that is sent by twitch?
Twitch sends a color tag with each message, so I can even update the code to display the username with the color from twitch too, but I'm not sure if this is preferred.

EDIT: I noticed that twitch actually just removes the `:` after the username and italicizes the message text, the coloring is done by 7tv. I can implement either one, or even just strip the `\u{1}ACTION` and not format the message.

**Comment by Xithrius** [comment]
I think coloring by twt would be best, and italicize the message along with it.
