### ISSUE TITLE
Emotes not rendering properly with Kitty on Ubuntu

### ISSUE THREAD

**Issue by mspi21** [Xithrius/twitch-tui#546]
**Describe the bug:**
When running the program in the Kitty terminal on Ubuntu with (any) emotes enabled, the emotes are downloaded successfully to the cache directory, but fail to render. Only coloured boxes are shown (see screenshot below).

**To Reproduce:**
On Ubuntu 23.10:
1. `sudo apt update && sudo apt install kitty`
2. `cargo install twitch-tui`
3. edit `.config/twt/config.toml` and enable emotes, set up your twitch account, etc.
4. join a chat, send or receive a message with an emote

**Expected behavior:**
Emotes are rendered as images.

**Screenshots:**

![Screenshot from 2024-03-01 21-32-48](https://github.com/Xithrius/twitch-tui/assets/78057064/3045b464-8696-4a30-86f8-5d2226967612)

**System:**
- Twitch-tui version: twitch-tui 2.6.4
- Operating System: Ubuntu 23.10 x86_64, linux 6.5.0-21-generic, GNOME 45.2
- Terminal: kitty 0.26.5
- Shell: GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)

**Comment by Nogesma** [comment]
Unicode placeholders are only supported from kitty 0.28.0. Ideally you would also need v0.31.0 at least for emote overlays.
Another option is to downgrade twt to 2.6.1

**Comment by mspi21** [comment]
> Unicode placeholders are only supported from kitty 0.28.0. Ideally you would also need v0.31.0 at least for emote overlays.
> 
> Another option is to downgrade twt to 2.6.1

Got it, thanks a lot for the quick reply. I will try upgrading kitty or downgrading twt and let you know if it resolves my problem.

**Comment by mspi21** [comment]
> > Unicode placeholders are only supported from kitty 0.28.0. Ideally you would also need v0.31.0 at least for emote overlays.
> > Another option is to downgrade twt to 2.6.1
> 
> Got it, thanks a lot for the quick reply. I will try upgrading kitty or downgrading twt and let you know if it resolves my problem.

For now, I downgraded twt, since it seemed like too much of a hassle to build kitty from source. In any case, it works now, thank you!

**Comment by Nogesma** [comment]
There is some executables directly available in the kitty github releases https://github.com/kovidgoyal/kitty/releases/tag/v0.32.2, the Linux amd64 binary bundle is probably the one you want.

**Comment by mspi21** [comment]
Thanks, I didn't notice there was a release bundle available. Now running newest versions of both kitty and twitch-tui and everything works perfectly :) Thanks again for the help, guys!
