### ISSUE TITLE
Uneven margins with only chat messages

### ISSUE THREAD

**Issue by calebaden** [Xithrius/twitch-tui#599]
**Describe the bug:**

Trying to achieve a minimal chat window results in empty space on the top and bottom of screen because the chat area does not update when the options `title_shown` and `state_tabs` are disabled and when not in insert mode.

**To Reproduce:**

1. Set `title_shown = false` in config
2. Set `state_tabs = false` in config
3. Join any chat lobby in `twt`
4. Observe empty lines on top and bottom of window when **not** in insert mode

**Expected behavior:**

Chat messages should use entire area of terminal like other terminal applications.

**Screenshots:**

![2024-05-17-082154_hyprshot](https://github.com/Xithrius/twitch-tui/assets/17247320/6b0ab627-2df2-4473-9072-1bd977414c95)
![2024-05-17-081755_hyprshot](https://github.com/Xithrius/twitch-tui/assets/17247320/73207a46-a929-40b7-b1bb-ad7382b20805)

**System:**

- Twitch-tui version: 2.6.8

- Operating System: Arch Linux w/ kernel 6.9.0

- Terminal: foot 1.17.2

- Shell: zsh 5.9

**Additional context:**

**Comment by Xithrius** [comment]
Thanks for the issue! I'll see what I can do to fix this.

**Comment by Xithrius** [comment]
Did you happen to modify the config variable `hide_chat_border`? I managed to forget to put it in the default config in the repository, although it should be there when generating a local config. This doesn't solve your issue, I'm just making sure.

**Comment by calebaden** [comment]
Yes, it was there when I generated a local config and I changed it to `true`

**Comment by Xithrius** [comment]
Fixed, available in the release linked below. Feel free to reopen this issue if it's still broken.

https://github.com/Xithrius/twitch-tui/releases/tag/v2.6.9
