### ISSUE TITLE
Uppercase characters for twitch names

### ISSUE THREAD

**Issue by calebaden** [Xithrius/twitch-tui#601]
**Is your feature request related to a problem? Please describe.**
I'm wondering if it's possible to maintain uppercase characters on twitch usernames. It really hinders readability of the chat with certain names such as `theRealDJ` when they are always printed in lowercase. It seems inconsistent since uppercase characters are used in the messages themselves including mentions of usernames, eg;
`therealdj: @theRealDj Hello World`

**Describe the solution you'd like**
Usernames maintain their uppercase characters;
`theRealDJ: @theRealDj Hello World`

**Describe alternatives you've considered**
nil

**Additional context**
nil

**Comment by calebaden** [comment]
I was just testing out some options and it seems this is actually a bug. With badges enabled usernames do have uppercase characters, but with badges disabled all usernames are lowercase.

![2024-05-20-095548_hyprshot](https://github.com/Xithrius/twitch-tui/assets/17247320/e9de1d22-8ab1-4923-b05b-d63fba5ffd1f)

**Comment by Xithrius** [comment]
Yeah, I just found that out as well lol. I've also found out why it's happening internally, so I'll fix it and get a release going.

**Comment by Xithrius** [comment]
Fix is available in https://github.com/Xithrius/twitch-tui/releases/tag/v2.6.10
