### ISSUE TITLE
Unable to use the emote picker on macOS.

### ISSUE THREAD

**Issue by mtane0412** [Xithrius/twitch-tui#625]
**Describe the bug:**
The `Alt + e` key implements an emote picker in #506, but there is no Alt key in macOS. The alternative `option + e` is used as a modifier key for accents. I have tried other modifier keys, but nothing happens.

**To Reproduce:**
1. Go to input mode with kitty on macOS
2. press `Option + e`
3. nothing happens.  If you type alphabets continuously, they will be entered with accents. (ex. `é` )

**Expected behavior:**
emote picker opens

**Screenshots:**
![](https://i.gyazo.com/bf9080fee844376f099b6d05e40541fb.gif)

**System:**
- Twitch-tui version:2.6.13

- Operating System: macOS Sonoma Version 14.2.1

- Terminal: Kitty 14.2.1

- Shell: zsh 5.9 (x86_64-apple-darwin23.0)

**Additional context:**
I use M2 Macbook Air and US Keyboard, Japanese Input System.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_option_as_alt

**Comment by mtane0412** [comment]
@kovidgoyal 
That was exactly the solution! Thanks, my problem is solved.

**Comment by Xithrius** [comment]
I'll be sure to add this in the documentation, just in case it happens to other users.
