### ISSUE TITLE
Feature request: NO_COLOR standard implementation

### ISSUE THREAD

**Issue by hellishvictor** [Xithrius/twitch-tui#629]
Hi, it would be great implement the NO_COLOR standard on **twitch-tui** since there's many  CLI already with it (**jaq**, **miller**, **crop**, **upx**, **python**, **xq**, etc..,) and save the users from use "color=never", "--monochrome-color" or whatever.

```
Command-line software which adds ANSI color to its output by default should check
 for a NO_COLOR environment variable that, when present and not an empty string
 (regardless of its value), prevents the addition of ANSI color.

By adopting this standard, users that prefer to have plain, non-colored text output
 can export NO_COLOR=1 to their shell’s environment and automatically disable color
 by default in all supported software.

If your software outputs color by default, please consider not doing so. 

More info on: https://no-color.org/
```
Cheers

**Comment by Xithrius** [comment]
Thank you for the feature suggestion. I see no problem with implementing this. Hopefully I can get it done within the next week or so.

**Comment by Xithrius** [comment]
Started development with draft PR https://github.com/Xithrius/twitch-tui/pull/632

**Comment by Xithrius** [comment]
Sorry for the wait. This feature is now available in https://github.com/Xithrius/twitch-tui/releases/tag/v2.6.14. Please let me know if I've missed anything. Thanks!

**Comment by hellishvictor** [comment]
Hi, glad that finally is implemented, but seems that it's bypassed when there's an error and shows:
```
Message:  ←[36mcalled `Result::unwrap()` on an `Err` value:
   0: ←[91mConfiguration error.←[0m
   1: ←[91mTwitch config section is missing one or more of the following: username, channel, token.←
[0m

Location:
   ←[35msrc\handlers\config.rs←[0m:←[35m514←[0m

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: ←[32mBaseThreadInitThunk←[0m←[90m<unknown>←[0m
      at ←[35m<unknown source file>←[0m:←[35m<unknown line>←[0m
   2: ←[91mRtlUserThreadStart←[0m←[90m<unknown>←[0m
      at ←[35m<unknown source file>←[0m:←[35m<unknown line>←[0m

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.←[0m
Location: ←[35msrc/main.rs←[0m:←[35m76←[0m

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: ←[32mBaseThreadInitThunk←[0m←[90m<unknown>←[0m
      at ←[35m<unknown source file>←[0m:←[35m<unknown line>←[0m
   2: ←[91mRtlUserThreadStart←[0m←[90m<unknown>←[0m
      at ←[35m<unknown source file>←[0m:←[35m<unknown line>←[0m

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```
I've already set up the "COLORBT_SHOW_HIDDEN=1"  enviroment variable.
Cheers.

**Comment by hellishvictor** [comment]
Hi, glad that finally is implemented, but seems that still something is missing out:
![sshot-1](https://github.com/user-attachments/assets/d4e97bcc-6a3a-43f7-bf31-e1088b690b32)

And here is how it shows when there's an error:
![sshot-2](https://github.com/user-attachments/assets/b1b932bc-f43d-4a92-8eb5-d94d69c9aa40)

I've already set up the "COLORBT_SHOW_HIDDEN=1"  enviroment variable.
Cheers.

**Comment by Xithrius** [comment]
Besides the winapi error, looks like there's a problem with the config. Could you send it, excluding the token? Thanks.

**Comment by Xithrius** [comment]
Looks like the first section here is missing, which is what the error is coming from.

https://github.com/Xithrius/twitch-tui/blob/main/default-config.toml#L1-L13

**Comment by hellishvictor** [comment]
Yes, it's there, but as the token is excluded and the other two items in there are the username and channel, I just didn't include that section; however I should have mention that.

**Comment by Xithrius** [comment]
What windows version are you on? I think I might know of a solution, it just seems like underlining text isn't supported(?), possible way to fix is just not having underlines anywhere in the code. I'll be able to test this later.

**Comment by hellishvictor** [comment]
I'm on Windows 7 SP1 x64. [Jaq](https://github.com/01mf02/jaq/issues/177) have a similar issue and fixed it.

**Comment by CharlesBuell** [comment]
I'm seeing issues in other applications where the same problem exists. I'll attempt to fix soonish.

**Comment by Xithrius** [comment]
I'm seeing issues with the same problem you're describing. I'll see if I can get a fix going soonish.

**Comment by Xithrius** [comment]
Could you create a new issue for this? Thanks.

**Comment by hellishvictor** [comment]
Done.
