### ISSUE TITLE
Problem on console without support of color

### ISSUE THREAD

**Issue by hellishvictor** [Xithrius/twitch-tui#648]
Here on Win 7 x64 SP1 it shows errors:

![353107439-d4e97bcc-6a3a-43f7-bf31-e1088b690b32](https://github.com/user-attachments/assets/7464df50-bb95-4d9a-9dbd-602d956e84cf)
![353109301-b1b932bc-f43d-4a92-8eb5-d94d69c9aa40](https://github.com/user-attachments/assets/92aa91c1-13f3-40d6-88d9-b9ddc53ce6ba)

Cheers.

**Comment by CharlesBuell** [comment]
(Tracking issue based off of https://github.com/Xithrius/twitch-tui/issues/629#issuecomment-2256077185)

**Comment by Xithrius** [comment]
(Tracking issue based off of https://github.com/Xithrius/twitch-tui/issues/629#issuecomment-2256077185)

**Comment by Xithrius** [comment]
https://github.com/Xithrius/twitch-tui/issues/629

**Comment by Xithrius** [comment]
#629

**Comment by Xithrius** [comment]
In the last issue that was tracking this you had a config with everything needed, but this error is saying that you're missing a section. Are you sure you placed it in the right path? Also, regardless of if `NO_COLOR` is enabled or not, I don't specify underlining in any of the styles besides `ctrl + f` highlighting, which isn't enabled by default. I'm not too sure what's causing this issue, and I don't really have a direct way of reproducing it either.

**Comment by Xithrius** [comment]
Nevermind I believe I've found the issue, but it's going to take a while to fix.

**Comment by Xithrius** [comment]
I believe I've fixed the problem in the release linked below. If not, feel free to re-open this issue.

https://github.com/Xithrius/twitch-tui/releases/tag/v2.6.16

**Comment by hellishvictor** [comment]
Now it works ! Thank you very much, you're god !

**Comment by Xithrius** [comment]
No problem. Have a good one!
