### ISSUE TITLE
error in book

### ISSUE THREAD

**Issue by sweiglbosker** [Xithrius/twitch-tui#654]
on [this](https://xithrius.github.io/twitch-tui/keybinds/index.html) page, there is a broken link to the dashboard page which im pretty sure is not supposed to be there. it is missing in the sidebar and the [markdown file](https://github.com/Xithrius/twitch-tui/blob/main/book/src/SUMMARY.md) but somehow still appears on the website

**Comment by Xithrius** [comment]
Fixed. Thanks!
