### ISSUE TITLE
Panicked at tokio::select

### ISSUE THREAD

**Issue by balroggg** [Xithrius/twitch-tui#83]
Sometimes app panicked at `tokio::select`, app does not get any messages.
```
thread 'tokio-runtime-worker' panicked at 'all branches are disabled and there is no else branch', src/twitch.rs:56
```

git commit a4e26b3b18eb78cb65d032c57875a4b2a36ff9cf

**Comment by Xithrius** [comment]
I shall attempt to fix this.
