### ISSUE TITLE
Add support of twitch badges

### ISSUE THREAD

**Issue by balroggg** [Xithrius/twitch-tui#84]
We have no support of twitch badges, we can not differentiate users in chat.

Will be good to support this behavior by adding badges like in `stream chat`.

Possible steps to solve the issue:
- [ ] Add config/cli argument to enable/disable showing badges(badges = on/off)
- [ ] Get badge status (mods/subs/prime or others)
- [ ] Render badges by Unicode emotes

**Comment by balroggg** [comment]
Example message from user with badge prime gaming
```
👑Username | Hello chat!
```

**Comment by Xithrius** [comment]
Stalled until #74 is merged.

**Comment by Xithrius** [comment]
@balroggg the previously mentioned PR has been merged, will you still be able to work on this feature?

If not, could you tell me how you were going to go about it so I'd be able to implement it myself?

Thanks!

**Comment by balroggg** [comment]
@Xithrius ok thanks, I will check new changes and try to create PR on this.

**Comment by balroggg** [comment]
https://github.com/Xithrius/twitch-tui/pull/108
Add badges, no configure support
