### ISSUE TITLE
Switch from `Clap` to `StructOpt`.

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/twitch-tui#96]
Less convoluted documentation and integration with this application.

[Here](https://docs.rs/structopt/latest/structopt/) is the documentation.

I'll be putting this into the 2.0 release.

@balroggg I think you brought this up at some point about how clap removed the ability to use a `yml` config file, so this is the solution.

[main.rs](https://github.com/Xithrius/twitch-tui/blob/main/src/main.rs#L16-L49) and [cli.yml](https://github.com/Xithrius/twitch-tui/blob/main/cli.yml) will be converted to some structure.

**Comment by kshpin** [comment]
I'd like to tackle this one
